### ISSUE TITLE
加密

### ISSUE THREAD

**Issue by Kewl-csj** [397179459/SigninTools#1]
请问这个问题是什么原因？ValueError: Data must be aligned to block boundary in ECB mode
由于不会配置AES密钥，选择使用明文
我是在自己电脑的pycharm上跑的

**Comment by 397179459** [comment]
贴一下 `my_config/com_config.py`文件里怎么配置的

**Comment by 397179459** [comment]
你是运行哪个文件报的错。你在core/common_util/private_crypt.py #19打个断电

**Comment by Kewl-csj** [comment]
运行tieba_signin.py报的错，断点打了，有生成密钥
<img width="778" alt="image" src="https://github.com/397179459/SigninTools/assets/74132272/5ba6165b-abf2-4ced-bfc1-3b314363883d">

**Comment by 397179459** [comment]
是在`private_crypt.py` #43 抛的异常吗？
我试了很多方法，都没有复现你的报错。建议你删除配置，重新设置一个密钥，从budss.py重新配置一下，再运行。

**Comment by Kewl-csj** [comment]
重新配置后，密钥未报错了。但这个has_more不存在开始报错
<img width="695" alt="image" src="https://github.com/397179459/SigninTools/assets/74132272/af0e37a7-b431-45f2-9119-ac7f5306f4de">
<img width="764" alt="image" src="https://github.com/397179459/SigninTools/assets/74132272/81a57a36-2180-488f-a602-7ade35457af0">
like_response中不存在has_more和forum_list

**Comment by 397179459** [comment]
你确定配置的bduss对吗，你debug的时候看一下like_resoponse，应该没获取到你的贴吧列表吧。

**Comment by Kewl-csj** [comment]
终于成功了，谢谢你🤣 然后这个py文件是要每天运行一次吗

**Comment by 397179459** [comment]
`.github/workflows/baidu_tieba.yml` 这里设置actions，actions还需要enable，你自己百度一下吧。

**Comment by 397179459** [comment]
> <img alt="image" width="609" src="https://user-images.githubusercontent.com/74132272/266261133-a573e951-a178-4697-b02c-149bfe73c8cc.png">

这个图片删一下吧，里面有你的push密钥
